framework:
  translator:
    fallback:           en
    paths:
      - '%kernel.root_dir%/../translations'
  secret:             %secret%
  router:
    resource:              "%kernel.root_dir%/config/routing/routing.yml"
    strict_requirements:   ~
  form:                    true
  csrf_protection:         true
  validation:
      enable_annotations:  true
  templating:
    engines:              ['twig']
    #assets_version:      SomeVersionScheme

  default_locale:          %locale%
  session:
    save_path:           %kernel.project_dir%/var/sessions

  fragments:               ~
  trusted_hosts:           ~
  trusted_proxies:         ~
  http_method_override:    true
