services:
  monolog.formatter.default:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%%\n"

monolog:
  channels: ['app.command']
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: [!event]
      formatter: monolog.formatter.default
    console:
      type:   console
      level: debug
      channels: [!event, !doctrine]
      formatter: monolog.formatter.default
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type:   firephp
    #    level:  info
    #chromephp:
    #    type:   chromephp
    #    level:  info
