imports:
    - { resource: config.yml }
    - { resource: parameters/parameters_dev.yml }
    - { resource: bundles/monolog_dev.yaml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
