imports:
  - { resource: parameters/parameters_base.yml }
  - { resource: bundles/sonata_admin.yml }
  - { resource: bundles/sonata_block.yml }
  - { resource: bundles/framework.yml }
  - { resource: bundles/stof.yml }
  - { resource: security.yml }

# Twig Configuration
twig:
  form_themes:
    - 'bootstrap_3_layout.html.twig'

  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

doctrine:
  dbal:
    default_connection: default

    connections:
      default:
          driver:   %database_driver%
          dbname:   %database_name%
          user:     %database_user%
          host:     %database_host%
          password: %database_password%
          charset:  UTF8
          server_version: 5.5 # to avoid https://github.com/doctrine/DoctrineBundle/issues/351

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    default_entity_manager: "default"

    # When using Entities outside the default S2 dir structur mapping needs to be done by hand
    entity_managers:
      default:
        default_repository_class: Components\Repository\DefaultDoctrine
        auto_mapping: false
        naming_strategy: "doctrine.orm.naming_strategy.underscore"

        mappings:
            core_bundle:
                type: yml
                prefix: AppBundle\Model
                dir: "%kernel.project_dir%/src/AppBundle/Resources/config/doctrine"
                alias: AppBundle
                is_bundle: false
